Q.1
SELECT *
FROM EMPLOYEE
ORDER BY LEVELS DESC
LIMIT 1;

Q.2
SELECT COUNT(*) AS C,
	BILLING_COUNTRY
FROM INVOICE
GROUP BY BILLING_COUNTRY
ORDER BY C DESC Q.3 WHAT ARE THE TOP 3
VALUES OF INVOICE
SELECT TOTAL
FROM INVOICE
ORDER BY TOTAL DESC
LIMIT 3;

Q.4
SELECT SUM (TOTAL) AS INVOICE_TOTAL,
	BILLING_CITY
FROM INVOICE
GROUP BY BILLING_CITY
ORDER BY INVOICE_TOTAL DESC 

Q 5.
SELECT C.CUSTOMER_ID,
	C.FIRST_NAME,
	C.LAST_NAME,
	SUM(INVOICE.TOTAL) AS TOTAL
FROM CUSTOMER C
JOIN INVOICE ON C.CUSTOMER_ID = INVOICE.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID
ORDER BY TOTAL DESC
LIMIT 1;