#1. What are the details of all cars purchased in the year 2022?
SELECT C.Car_id,c.make,c.style,c.type,c.cost_$, s.purchase_date as cars_purchased_in_2022
from cars c
join sales s
on c.car_id=s.car_id
where year (purchase_date)=2022;

#2. What is the total number of cars sold by each salesperson?
select sp.name, count(s.sale_id) as num_of_cars_sold_by_each_salesperson
from salespersons sp
join sales s
on sp.salesman_id=s.salesman_id
group by sp.name;

#3. What is the total revenue generated by each salesperson?

SELECT	SP.NAME AS SALESPERSON_NAME,
		SUM(C.COST_$) AS TOTAL_REVENUE
FROM	SALESPERSONS SP
JOIN	SALES S
ON		SP.SALESMAN_ID = S.SALESMAN_ID
INNER JOIN CARS C
ON		S.CAR_ID = C.CAR_ID
GROUP BY SP.NAME;
#ORDER BY 2;

#4. What are the details of the cars sold by each salesperson?
select  sp.name, c.car_id,c.type,c.make,c.style,c.cost_$
from salespersons sp
join sales s
on sp.salesman_id=s.salesman_id
join cars c
on s.car_id=c.car_id
group by sp.name;

#5. What is the total revenue generated by each car type?
select type, sum(cost_$) as renenue_generated
from cars 
group by type;

#6. What are the details of the cars sold in the year 2021 by salesperson 'Emily Wong'?
 
 SELECT	SP.NAME,
		C.MAKE, C.TYPE, C.STYLE, C.COST_$
FROM	SALESPERSONS SP
JOIN	SALES S
ON		SP.SALESMAN_ID = S.SALESMAN_ID
JOIN	CARS C
ON		S.CAR_ID = C.CAR_ID
WHERE	YEAR(S.PURCHASE_DATE) = 2021 AND SP.NAME = 'EMILY WONG';

#7. What is the total revenue generated by the sales of hatchback cars?
select c.style ,sum(c.cost_$) as TOTAL_HATCHBACK_REVENUE
from cars c
where style ='hatchback';

#8. What is the total revenue generated by the sales of SUV cars in the year 2022?
select   c.style, sum(c.cost_$) as 2022_SUV_REVENUE
FROM CARS c
JOIN SALES s
ON C.CAR_ID=S.CAR_ID
WHERE YEAR(s.purchase_date)=2022 and c.style='SUV';

#9. What is the name and city of the salesperson who sold the most number of cars in the year 2023?
select sp.name,sp.city, count(c.car_id) as number_of_cars_sold,s.purchase_date
from salespersons sp
join sales s
on sp.salesman_id=s.salesman_id
join cars c
on s.car_id=c.car_id
where year(purchase_date)=2023
group by sp.name,sp.city
order by number_of_cars_sold desc
limit 1;

#10. What is the name and age of the salesperson who generated the highest revenue in the year 2022?
select sp.name,sp.age,sum(c.cost_$) as highest_revenue
from salespersons sp
join sales s
on sp.salesman_id=s.salesman_id
join cars c
on s.car_id=c.car_id
where year(purchase_date)=2022
group by sp.name,sp.age
order by highest_revenue desc
limit 1;

